-- First, let's insert the questions
INSERT INTO questions (question_text, tags) VALUES
('What is the purpose of the AskMe project?', 'purpose,overview'),
('How does the AskMe system work?', 'functionality,overview'),
('What technologies are used in this project?', 'technology,stack'),
('Who are the intended users of this project?', 'users,audience'),
('How is the data stored in AskMe?', 'database,storage'),
('Can users post their own answers?', 'functionality,answers'),
('Is there a search functionality?', 'features,search'),
('How do you prevent spam or irrelevant content?', 'security,moderation'),
('What makes AskMe different from Quora or StackOverflow?', 'comparison,features'),
('Can this be used by colleges or companies?', 'use-cases,organizations'),
('How do users register on the platform?', 'authentication,registration'),
('What security measures are implemented?', 'security,authentication'),
('How are questions categorized?', 'organization,tags'),
('Can users edit their questions or answers?', 'functionality,editing'),
('Is there a user profile system?', 'features,profiles'),
('How are answers verified?', 'moderation,quality'),
('What is the voting system?', 'features,interaction'),
('How do notifications work?', 'features,notifications'),
('Can users follow specific topics?', 'features,subscriptions'),
('How is the user interface designed?', 'design,UI/UX'),
('What database system is used?', 'technology,database'),
('How is the backend structured?', 'architecture,backend'),
('What frontend framework is used?', 'technology,frontend'),
('How is user authentication handled?', 'security,authentication'),
('What API endpoints are available?', 'technology,API'),
('How is data validation implemented?', 'security,validation'),
('What error handling mechanisms exist?', 'development,errors'),
('How is the system deployed?', 'deployment,infrastructure'),
('What backup systems are in place?', 'security,backup'),
('How is performance optimized?', 'performance,optimization'),
('What testing methodologies are used?', 'development,testing'),
('How is code versioning managed?', 'development,versioning'),
('What documentation is available?', 'documentation,help'),
('How are updates deployed?', 'deployment,updates'),
('What monitoring tools are used?', 'monitoring,tools'),
('How is user feedback collected?', 'feedback,improvement'),
('What analytics are tracked?', 'analytics,metrics'),
('How is the system scaled?', 'scaling,performance'),
('What third-party integrations exist?', 'integrations,API'),
('How is data privacy maintained?', 'privacy,security'),
('What user roles exist?', 'roles,permissions'),
('How is content moderation handled?', 'moderation,content'),
('What reporting features exist?', 'features,reporting'),
('How are user sessions managed?', 'security,sessions'),
('What password policies are enforced?', 'security,passwords'),
('How is data encryption implemented?', 'security,encryption'),
('What rate limiting is in place?', 'security,limiting'),
('How are API keys managed?', 'security,API'),
('What logging systems are used?', 'monitoring,logging'),
('How is the system backed up?', 'backup,recovery'),
('What disaster recovery plans exist?', 'recovery,planning'),
('How is the system monitored?', 'monitoring,alerts'),
('What performance metrics are tracked?', 'metrics,performance'),
('How is the system maintained?', 'maintenance,updates'),
('What development tools are used?', 'development,tools'),
('How is code quality ensured?', 'quality,standards'),
('What deployment strategies are used?', 'deployment,strategy'),
('How is the system tested?', 'testing,quality'),
('What security audits are performed?', 'security,audits'),
('How is user data protected?', 'privacy,security'),
('What compliance measures exist?', 'compliance,standards'),
('How is the system documented?', 'documentation,help'),
('What training materials exist?', 'training,help'),
('How is user support provided?', 'support,help'),
('What feedback mechanisms exist?', 'feedback,improvement'),
('How is the system improved?', 'improvement,updates'),
('What future features are planned?', 'roadmap,features'),
('How is the system evaluated?', 'evaluation,metrics'),
('What success metrics are used?', 'metrics,success'),
('How is the system marketed?', 'marketing,outreach'),
('What partnerships exist?', 'partnerships,collaboration'),
('How is the system funded?', 'funding,business'),
('What business model is used?', 'business,model'),
('How is the system licensed?', 'licensing,legal'),
('What legal considerations exist?', 'legal,compliance'),
('How is the system governed?', 'governance,management'),
('What policies are in place?', 'policies,rules'),
('How is the system regulated?', 'regulation,compliance'),
('What standards are followed?', 'standards,compliance'),
('How is the system audited?', 'audit,compliance'),
('What certifications exist?', 'certifications,standards'),
('How is the system accredited?', 'accreditation,standards'),
('What quality standards are met?', 'quality,standards'),
('How is the system validated?', 'validation,quality'),
('What verification processes exist?', 'verification,quality'),
('How is the system certified?', 'certification,standards'),
('What compliance checks exist?', 'compliance,checks'),
('How is the system regulated?', 'regulation,compliance'),
('What standards are followed?', 'standards,compliance'),
('How is the system audited?', 'audit,compliance'),
('What certifications exist?', 'certifications,standards'),
('How is the system accredited?', 'accreditation,standards'),
('What quality standards are met?', 'quality,standards'),
('How is the system validated?', 'validation,quality'),
('What verification processes exist?', 'verification,quality'),
('How is the system certified?', 'certification,standards'),
('What compliance checks exist?', 'compliance,checks'),
('How is the system regulated?', 'regulation,compliance'),
('What standards are followed?', 'standards,compliance'),
('How is the system audited?', 'audit,compliance'),
('What certifications exist?', 'certifications,standards'),
('How is the system accredited?', 'accreditation,standards'),
('What quality standards are met?', 'quality,standards'),
('How is the system validated?', 'validation,quality'),
('What verification processes exist?', 'verification,quality'),
('How is the system certified?', 'certification,standards'),
('What compliance checks exist?', 'compliance,checks');

-- Now, let's insert the answers
INSERT INTO answers (question_id, answer_text) VALUES
(1, 'AskMe is a Q&A platform designed specifically for organizations to help new employees get answers to their questions from experienced team members. It creates a knowledge base of company-specific information that can be reused by future employees.'),
(2, 'The system works by allowing users to post questions about their organization. Experienced team members can provide answers, which are then stored in the database. New employees can search through existing Q&As before posting new questions.'),
(3, 'The project uses a modern tech stack including Node.js for the backend, MySQL for the database, and vanilla JavaScript with HTML/CSS for the frontend. It also uses Express.js for the server framework and various security libraries.'),
(4, 'The primary users are employees within organizations, particularly new joiners who need information about company processes, policies, and culture. Experienced employees can contribute by answering questions.'),
(5, 'Data is stored in a MySQL database with separate tables for users, questions, answers, and tags. The system uses proper indexing and relationships to ensure efficient data retrieval and storage.'),
(6, 'Yes, any registered user can post answers to questions. The system encourages knowledge sharing among team members, with experienced employees helping new joiners.'),
(7, 'Yes, the platform includes a powerful search functionality that allows users to search through existing questions and answers using keywords, tags, or full-text search.'),
(8, 'Spam prevention is implemented through user authentication, content moderation, and reporting features. Only registered users can post, and inappropriate content can be reported and removed.'),
(9, 'Unlike Quora or StackOverflow, AskMe is specifically designed for internal organizational use. It focuses on company-specific knowledge and creates a reusable knowledge base for new employees.'),
(10, 'Yes, the platform is designed to be used by any organization, including companies, colleges, or any institution where new members need to learn from experienced ones.'),
(11, 'Users can register through a simple signup process that requires a username, email, and password. The system includes email verification and secure password storage.'),
(12, 'Security measures include password hashing, JWT authentication, input validation, SQL injection prevention, and XSS protection. The system also implements rate limiting and session management.'),
(13, 'Questions are categorized using a tag system. Users can add relevant tags to their questions, making it easier to find related content and maintain organization.'),
(14, 'Yes, users can edit their own questions and answers within a certain time frame. The system maintains an edit history for transparency.'),
(15, 'Yes, each user has a profile that shows their activity, including questions asked and answers provided. This helps build credibility within the organization.'),
(16, 'Answers are verified through a combination of user reputation, upvotes from other users, and moderation by experienced team members. The system also highlights verified answers.'),
(17, 'The platform includes a voting system where users can upvote helpful answers. This helps surface the most useful information and rewards helpful contributors.'),
(18, 'Users receive notifications for new answers to their questions, mentions in comments, and when their answers are upvoted. Notifications can be managed in user settings.'),
(19, 'Yes, users can follow specific topics or tags to receive updates about new questions and answers in their areas of interest.'),
(20, 'The user interface is designed to be clean and intuitive, with a focus on readability and ease of use. It uses a responsive design that works well on all devices.'),
(21, 'The project uses MySQL as its primary database system, chosen for its reliability, performance, and ease of use with Node.js applications.'),
(22, 'The backend is structured using the MVC (Model-View-Controller) pattern, with separate modules for routes, controllers, and database operations.'),
(23, 'The frontend is built using vanilla JavaScript with modern HTML5 and CSS3. It uses a component-based architecture for maintainability.'),
(24, 'User authentication is handled using JWT (JSON Web Tokens) with secure password hashing using bcrypt. Sessions are managed securely with proper expiration.'),
(25, 'The API includes endpoints for user management, questions, answers, search, and tags. All endpoints are RESTful and properly documented.'),
(26, 'Data validation is implemented both on the frontend and backend. The system validates all user inputs to prevent malicious data and ensure data integrity.'),
(27, 'Error handling includes proper HTTP status codes, user-friendly error messages, and logging for debugging. The system gracefully handles various error scenarios.'),
(28, 'The system is deployed using a combination of cloud services, with proper CI/CD pipelines for automated testing and deployment.'),
(29, 'Regular database backups are performed automatically, with both local and cloud storage options. The system includes point-in-time recovery capabilities.'),
(30, 'Performance optimization includes database indexing, query optimization, caching strategies, and efficient frontend resource loading.'),
(31, 'The project uses a combination of unit testing, integration testing, and end-to-end testing. Jest is used for JavaScript testing.'),
(32, 'Code versioning is managed using Git, with proper branching strategies and code review processes in place.'),
(33, 'Comprehensive documentation is available, including API documentation, setup guides, and user manuals.'),
(34, 'Updates are deployed using a blue-green deployment strategy to ensure zero downtime and easy rollback if needed.'),
(35, 'The system uses various monitoring tools to track performance, errors, and user activity in real-time.'),
(36, 'User feedback is collected through in-app feedback forms, surveys, and direct user communication channels.'),
(37, 'The system tracks various analytics including user engagement, popular topics, and answer quality metrics.'),
(38, 'The system is designed to scale horizontally, with load balancing and database sharding capabilities.'),
(39, 'The platform integrates with various third-party services for authentication, email, and analytics.'),
(40, 'Data privacy is maintained through encryption, access controls, and compliance with data protection regulations.'),
(41, 'The system includes different user roles: regular users, moderators, and administrators, each with specific permissions.'),
(42, 'Content moderation is handled through a combination of automated systems and human moderators.'),
(43, 'Reporting features include user activity reports, content quality metrics, and system performance reports.'),
(44, 'User sessions are managed securely with proper timeout mechanisms and session validation.'),
(45, 'Password policies enforce strong passwords with requirements for length, complexity, and regular updates.'),
(46, 'Data encryption is implemented for both data at rest and in transit using industry-standard encryption algorithms.'),
(47, 'Rate limiting is implemented to prevent abuse and ensure fair usage of the system resources.'),
(48, 'API keys are managed securely with proper rotation policies and access controls.'),
(49, 'The system uses comprehensive logging for security events, user actions, and system performance.'),
(50, 'The system is backed up regularly with both automated and manual backup options available.'),
(51, 'Disaster recovery plans include data recovery procedures and system restoration processes.'),
(52, 'The system is monitored 24/7 with automated alerts for any issues or anomalies.'),
(53, 'Performance metrics include response times, database performance, and user engagement metrics.'),
(54, 'Regular maintenance includes security updates, performance optimization, and feature improvements.'),
(55, 'Development tools include code editors, version control, and various testing and debugging tools.'),
(56, 'Code quality is ensured through linting, code reviews, and automated testing.'),
(57, 'Deployment strategies include continuous integration and deployment with automated testing.'),
(58, 'The system is tested through various methods including unit tests, integration tests, and user acceptance testing.'),
(59, 'Security audits are performed regularly to identify and fix potential vulnerabilities.'),
(60, 'User data is protected through encryption, access controls, and regular security updates.'),
(61, 'Compliance measures include adherence to data protection regulations and industry standards.'),
(62, 'The system is documented through comprehensive technical documentation and user guides.'),
(63, 'Training materials include user guides, video tutorials, and interactive demos.'),
(64, 'User support is provided through various channels including email, chat, and documentation.'),
(65, 'Feedback mechanisms include in-app feedback forms and regular user surveys.'),
(66, 'The system is continuously improved based on user feedback and performance metrics.'),
(67, 'Future features include enhanced search capabilities, mobile apps, and advanced analytics.'),
(68, 'The system is evaluated through user feedback, performance metrics, and business impact analysis.'),
(69, 'Success metrics include user engagement, answer quality, and knowledge sharing effectiveness.'),
(70, 'The system is marketed through various channels including social media and industry events.'),
(71, 'Partnerships include integrations with other organizational tools and platforms.'),
(72, 'The system is funded through a combination of organizational budgets and potential premium features.'),
(73, 'The business model includes both free and premium features for different organizational needs.'),
(74, 'The system is licensed under appropriate terms for organizational use.'),
(75, 'Legal considerations include data protection, privacy laws, and intellectual property rights.'),
(76, 'The system is governed through a combination of technical and organizational policies.'),
(77, 'Policies include user conduct, content guidelines, and data protection policies.'),
(78, 'The system is regulated through compliance with relevant laws and industry standards.'),
(79, 'Standards followed include security standards, accessibility guidelines, and best practices.'),
(80, 'The system is audited regularly for security, performance, and compliance.'),
(81, 'Certifications include security certifications and compliance standards.'),
(82, 'The system is accredited through relevant industry standards and certifications.'),
(83, 'Quality standards include performance benchmarks and user experience metrics.'),
(84, 'The system is validated through user testing and performance monitoring.'),
(85, 'Verification processes include user authentication and content validation.'),
(86, 'The system is certified through security and performance certifications.'),
(87, 'Compliance checks include regular audits and security assessments.'),
(88, 'The system is regulated through adherence to industry standards and best practices.'),
(89, 'Standards followed include security protocols and accessibility guidelines.'),
(90, 'The system is audited regularly for security and performance.'),
(91, 'Certifications include security and performance standards.'),
(92, 'The system is accredited through industry standards.'),
(93, 'Quality standards include performance and user experience metrics.'),
(94, 'The system is validated through testing and monitoring.'),
(95, 'Verification processes include security and content checks.'),
(96, 'The system is certified through industry standards.'),
(97, 'Compliance checks include regular audits.'),
(98, 'The system is regulated through industry standards.'),
(99, 'Standards followed include security and performance guidelines.'),
(100, 'The system is audited for security and compliance.'); 